#!/bin/bash

while :
do

# Check desktop
user=$(users | awk '{print $1}')
test -f "${XDG_CONFIG_HOME:-/home/$user/.config}/user-dirs.dirs" && source "${XDG_CONFIG_HOME:-/home/$user/.config}/user-dirs.dirs"
desktop_dir="${XDG_DESKTOP_DIR:-/home/$user/Desktop}"
desktop_folder="$(echo $desktop_dir | cut -d/ -f 3-)"
desktop_dir="/home/$desktop_folder"
echo "Desktop: $desktop_dir"

if [[ $(rpm -q regataos-oem) == *"x86"* ]]; then
	echo "In Live Mode"

	if test ! -e "$desktop_dir/trash.desktop"; then
		cd "$desktop_dir/"
		cp -f "/usr/share/kio_desktop/directory.trash" "trash.desktop"
		xdotool key F5
	fi

	if test ! -e "$desktop_dir/Home.desktop"; then
		cd "$desktop_dir/"
		cp -f "/usr/share/kio_desktop/DesktopLinks/Home.desktop" "Home.desktop"
		xdotool key F5
	fi

	if test ! -e "$desktop_dir/live-installer.desktop"; then
		cd "$desktop_dir/"
		ln -sf "/usr/share/regataos/regataos-oem/live-installer.desktop" "live-installer.desktop"
		xdotool key F5
	fi

elif [[ $(rpm -q calamares) == *"x86"* ]]; then
	echo "In post-installation..."

	if test -e "$desktop_dir/trash.desktop"; then
		cd "$desktop_dir/"
		rm -rf *.desktop
		xdotool key F5

	elif test -e "$desktop_dir/Home.desktop"; then
		cd "$desktop_dir/"
		rm -rf *.desktop
		xdotool key F5

	else
		if test -e "$desktop_dir/live-installer.desktop"; then
			cd "$desktop_dir/"
			rm -rf *.desktop
			xdotool key F5
		fi
	fi

	if [[ $user == *"visitante"* ]]; then
		ps -C calamares > /dev/null
		if [ $? = 1 ]
		then
			/usr/bin/live-installer start
		fi
	fi

else
	echo "System installed!"

	if test ! -e "$desktop_dir/trash.desktop"; then
		cd "$desktop_dir/"
		cp -f "/usr/share/kio_desktop/directory.trash" "trash.desktop"
		xdotool key F5
	fi

	if test ! -e "$desktop_dir/Home.desktop"; then
		cd "$desktop_dir/"
		cp -f "/usr/share/kio_desktop/DesktopLinks/Home.desktop" "Home.desktop"
		xdotool key F5
	fi

	if test ! -e "/usr/bin/calamares"; then
		echo "The operating system appears to be installed, goodbye!"
		rm -f "/usr/share/regataos/regataos-oem/regataos-oem-user"
		break
	fi
fi

   sleep 1
done
